[build]
  publish = "frontend/dist"
  functions = "backend/dist/netlify"
  command = "node scripts/inject_vars.js --platform=netlify"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["better-sqlite3", "pg", "mysql2", "cloudflare:sockets"]
  included_files = [
    "!api/**",
    "!backend/dist/worker/**",
    "!backend/dist/docker/**",
    "!backend/dist/vercel/**"
  ]

[functions."api"]

[functions."cron"]
  schedule = "0 2 * * *"
