name: Deploy to Netlify

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  netlify:
    runs-on: ubuntu-latest
    name: "Deploy to Netlify"
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Check Required Secrets
        run: |
          REQUIRED=(NETLIFY_AUTH_TOKEN NETLIFY_SITE_ID)
          for var in "${REQUIRED[@]}"; do
            if [ -z "${!var}" ]; then
              echo "❌ Error: $var is missing."
              exit 1
            fi
          done
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Build and Deploy to Netlify
        run: |
          npx netlify-cli deploy --build --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Success Notification
        run: echo "🚀 NodeAuth deployed successfully to Netlify!"
